[package]
name = "green_moon_2d"
version = "0.1.0"
authors = ["Willi Kappler <grandor@gmx.de>"]
license = "MIT"
repository = "https://github.com/willi-kappler/green_moon_2d"
description = "2D game engine"
readme = "README.md"
exclude = ["target"]
keywords = ["2d", "Game", "Engine"]
categories = ["Game"]
edition = "2018"

[dependencies]
thiserror = "1.0"
#pixels = "0.3.0"
#winit = "0.24.0"
#winit_input_helper = "0.9.0" # Maybe ?
#image = "0.23.14"

#serde = "1.0"
#serde_derive = "1.0"
#serde_json = "1.0"
#log = "0.4"
#log4rs = "0.8"

[profile.release]
lto = true
