project(
  'green_moon_2d',
  'cpp',
  version: '0.0.1',
  default_options: ['cpp_std=c++23', 'warning_level=3', 'buildtype=release']
)

# Define custom warning or optimization flags
extra_flags_gcc_clang = [
  '-march=native',

  '-Wdouble-promotion',
  '-Wformat=2',
  '-Wundef',
  '-Wcast-qual',
  '-Woverloaded-virtual',
  '-Wuninitialized',
  '-Winit-self',
  '-Wredundant-decls',
  '-Wsuggest-override',
  '-Wshadow',
  '-Wnon-virtual-dtor',
  '-Wold-style-cast',
  '-Wcast-align',
  '-Wunused',
  '-Wconversion',
  '-Wsign-conversion',

  '-Wextra-semi',
  '-Wctor-dtor-privacy',
  '-Wzero-as-null-pointer-constant',
  '-Wlogical-op',
  #'-Wfloat-equal',
  '-Wpessimizing-move',
  '-Wredundant-move'
]

extra_flags_gcc = [
  '-Ofast',
  '-Walloca',
  '-Wcast-align=strict',
  '-Wimplicit-fallthrough=5',
  '-Wduplicated-cond',
  '-Wduplicated-branches',
  # '-Wuseless-cast',
  '-Wtrampolines'
]

extra_flags_clang = [
  '-O3 -ffast-math',
  '-Wimplicit-fallthrough',
  '-Wshadow-field',
  '-Wabstract-final-class',
  '-Wheader-hygiene'
]

extra_flags_msvc = [
  '/Wall',
  '/W4',
  '/w14242',
  '/w14265',
  '/w14287',
  '/we4289',
  '/w14296',
  '/w14311',
  '/utf-8'
]

# Safely check which flags are supported by the active compiler
cpp_compiler = meson.get_compiler('cpp')

if cpp_compiler.get_id() == 'gcc'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_gcc_clang + extra_flags_gcc)
elif cpp_compiler.get_id() == 'clang'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_gcc_clang + extra_flags_clang)
elif cpp_compiler.get_id() == 'msvc'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_msvc)
endif

# Point the include directory to 'src'
inc_dir = include_directories('src/gm2d')

# Source files
sources = files(
  'src/gm2d/gm2d.cpp',
  'src/gm2d/gm_animation.cpp',
  'src/gm2d/gm_bitmapfont.cpp',
  'src/gm2d/gm_bitmaptext.cpp',
  'src/gm2d/gm_configuration.cpp',
  'src/gm2d/gm_context.cpp',
  'src/gm2d/gm_math.cpp',
  'src/gm2d/gm_message.cpp',
  'src/gm2d/gm_object.cpp',
  'src/gm2d/gm_resources.cpp',
  'src/gm2d/gm_scene.cpp',
  'src/gm2d/gm_sprite.cpp',
  'src/gm2d/gm_texture.cpp',
  'src/gm2d/gm_timer.cpp'
)

# External dependencies:

# Import the CMake module
cmake = import('cmake')

# Configure taocpp-json as a CMake subproject
tao_json_sub = cmake.subproject('taocpp-json')
# Get the dependency target generated by CMake
tao_json_dep = tao_json_sub.dependency('taocpp-json', include_type: 'system')

# SDL3:
sdl3_dep = dependency('sdl3', fallback: ['sdl3', 'sdl3_dep'])
sdl3_image_dep = dependency('sdl3_image', fallback: ['sdl3_image', 'sdl3_image_dep'])

# For unit testing:
snitch_dep = dependency('snitch', fallback: ['snitch', 'snitch_dep'])

# Build the library
lib = shared_library(
  'green_moon_2d',
  sources,
  include_directories: inc_dir,
  override_options: ['werror=true', 'b_lto=true'],
  cpp_args: supported_flags_lib,
  dependencies: [tao_json_dep, sdl3_dep, sdl3_image_dep],
  install: true
)

# Declare dependency for other targets/projects
green_moon_2d_dep = declare_dependency(
  include_directories: inc_dir,
  link_with: lib
)

# Explicitly list header files to install them to system paths
install_headers(
  'src/gm2d/gm2d.hpp',
  'src/gm2d/gm_animation.hpp',
  'src/gm2d/gm_bitmapfont.hpp',
  'src/gm2d/gm_bitmaptext.hpp',
  'src/gm2d/gm_configuration.hpp',
  'src/gm2d/gm_context.hpp',
  'src/gm2d/gm_exceptions.hpp',
  'src/gm2d/gm_math.hpp',
  'src/gm2d/gm_message.hpp',
  'src/gm2d/gm_message_type.hpp',
  'src/gm2d/gm_object.hpp',
  'src/gm2d/gm_resources.hpp',
  'src/gm2d/gm_scene.hpp',
  'src/gm2d/gm_sprite.hpp',
  'src/gm2d/gm_string_id.hpp',
  'src/gm2d/gm_texture.hpp',
  'src/gm2d/gm_timer.hpp'
)

# Unit test configuration
test_sources = files(
  'tests/test_all.cpp',
  'tests/test_animation.cpp',
  'tests/test_configuration.cpp',
  'tests/test_math.cpp',
  'tests/test_string_id.cpp',
  'tests/test_timer.cpp'
)

test_exe = executable(
  'green_moon_2d_tests',
  test_sources,
  include_directories: include_directories('src'),
  dependencies: [green_moon_2d_dep, snitch_dep, tao_json_dep],
  # override_options: ['werror=true'],
  cpp_args: supported_flags_lib
)

test('all unit tests', test_exe)
