[setup]
scenes = [
    "scenes/main_menu.toml",
    "scenes/config_menu.toml",
    "scenes/highscore_menu.toml",
    "scenes/credits_menu.toml"
]
first_scene = "main_menu"
exit_on_window_close = true
fonts = "assets/fonts/fonts.toml"
